### ISSUE TITLE
Firestore에서 Task를 서브콜렉션으로 분리하여 Board와 별도 쿼리할 수 있음

### ISSUE THREAD

**Issue by BumgeunSong** [BumgeunSong/Krello#56]
## 해야할 일 목록
- [ ] FireStore에서 Task를 Board의 서브콜렉션으로 변경

## 설명
- 현재 Board를 가져오는 것은 BoardVC, Task를 가져오는 것은 TaskVC로 구분되어있는 상황임.
- 데이터를 서브콜렉션으로 분리하면 매번 같이 쿼리할 필요없이 별도 쿼리가 가능해짐.
- Task에 만약에 이후에 무거운 데이터가 들어가게 되면, 하나의 다큐먼트에 다 담았을 때 다큐먼트의 쿼리 성능이 저하됨.
- Tasks라는 서브 콜렉션을 만들고 Task를 다큐먼트로 저장하는 게 더 낫다고 판단이 되었음.

참고 - [Firestore의 데이터 구조 설계 시 알아야할 것](https://bumgeunsong.notion.site/Firestore-fae97184977c4ff5b4f63ae9f25ca70b)

**Comment by Jinsujin** [comment]
정리자료 보니 Task 를 필드라 아닌 document 로 분리하는 방향이 좋다고 생각되어 져요
task 는 데이터가 늘어날 가능성이 다분하므로, 용량제한/검색을 위해 분리하는 것도 좋을 것 같습니다.
Board 다큐먼트에 모든 Task 가 들어 있는데, Task 를 따로 분리 한다면 
1. status 에 따라 데이터를 가져올 수 도 있고
2. update, delete 를 할때 원하는 데이터를 빠르게 찾아 연산하기도 좋아보입니다
과금 되는 부분은 아직 사용자가 그리 많이 않아서 고려할 사항이 아니라고 판단...
구조 변경 찬성이요! 🙌🏼

**Comment by TaeKyeongKim** [comment]
그럼 board 에서 지금 log 있는것처럼 task 를 컬렉션으로 만든단 이야기져?
