### ISSUE TITLE
Readmd 작성하기

### ISSUE THREAD

**Issue by Jinsujin** [BumgeunSong/Krello#61]
# Krello

![iOS 13.0+](https://img.shields.io/badge/iOS-13.0%2B-lightgrey) ![Xcode 13.3](https://img.shields.io/badge/Xcode-13.3-blue)

> Trello-style Task Management App
> 기한: 2022.05.04 ~ 05.20 (13일)
> 프로젝트에 대한 자세한 내용은 [👉 Notion](https://cookie-giant-a00.notion.site/Team-KRE-Krello-4a6dfb5c5ccb4e19bd2f2d3fe066f57a) 에서 확인할 수 있습니다

## 앱 소개

[Trello](https://trello.com/) 의 기능을 따라 할일을 관리하는 iOS Application을 만들어 보았습니다.
구현된 기능은 다음과 같습니다:

- 회원 가입과 로그인 기능 구현
- CRUD 중 Read 구현

|                                                                                                                             로그인                                                                                                                             |                                                                                               회원가입                                                                                               |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
|                                                         ![login](https://user-images.githubusercontent.com/12508578/169458093-d3af10aa-0eb4-40df-ae8a-e8b0241e3e20.png)                                                            |                                           ![signup](https://user-images.githubusercontent.com/12508578/169457888-b24c62fc-9301-4a28-aa0e-081f79b083c3.gif)                                           |
| - Firebase authentication 을 사용해 email 로그인을 할 수 있습니다. <br/>- 로그인을 하면 firebase 로 부터 인증을 하고 받아온 사용자 uid 를 local 에 저장해 API 호출에 사용합니다. <br/>- 한번 로그인을 하면 앱 종료 후 다시 실행해도 로그인 상태를 유지합니다. | - email, password 로 회원가입을 할 수 있습니다. <br/>- 입력값에 대한 검증을 하고 유효한 값인지 체크합니다. <br/>- 모든 TextField 의 값이 유효하다고 판단이 되면 비로소 회원가입 버튼이 활성화됩니다. |

|                                                    할일 관리                                                    |                                                   드래그 앤 드랍                                                   |
| :-------------------------------------------------------------------------------------------------------------: | :----------------------------------------------------------------------------------------------------------------: |
| ![Board](https://user-images.githubusercontent.com/12508578/169457961-67a38d95-2543-407d-9671-280d22231747.gif) | ![TaskMove](https://user-images.githubusercontent.com/12508578/169458030-758b38a1-2583-497b-a035-d7bdd2a3ad3e.gif) |
|                - 사용자 키(uid) 에 해당하는 데이터를 firestore 로 부터 불러와 화면에 보여줍니다.                |                 - Drag & Drop 으로 할일을 이동시킬 수 있습니다.(서버에 반영하는 작업은 구현 안됨)                  |

### 팀원

| [@Eddy](https://github.com/BumgeunSong)                                                    | [@Kai](https://github.com/TaeKyeongKim)                                                    | [@Rosa](https://github.com/Jinsujin)                                                       |
| ------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------ |
| <img src="https://avatars.githubusercontent.com/u/17468015?v=4" width="200" height="200"/> | <img src="https://avatars.githubusercontent.com/u/36659877?v=4" width="200" height="200"/> | <img src="https://avatars.githubusercontent.com/u/12508578?v=4" width="200" height="200"/> |
|[👉 프로젝트 회고](https://github.com/BumgeunSong/Krello/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%9A%8C%EA%B3%A0:-@Eddy)                                                                               | [👉 프로젝트 회고](https://github.com/BumgeunSong/Krello/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%9A%8C%EA%B3%A0:-@Kai)                                                                                   | [👉 프로젝트 회고](https://github.com/BumgeunSong/Krello/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%ED%9A%8C%EA%B3%A0:-@Rosa)                                                                                   |

<br/>

### 사용한 기술

- [Unit Test](https://github.com/BumgeunSong/Krello/wiki/1.-%EB%8B%A8%EC%9C%84-%ED%85%8C%EC%8A%A4%ED%8A%B8)
- [View](https://github.com/BumgeunSong/Krello/wiki/2.-%EB%B7%B0)
  - Autolayout programmatically
  - Compositional Layout
- [Firebase: Authentication & Storage](https://github.com/BumgeunSong/Krello/wiki/3.-Firebase-(Back-end))
- [Coordinator pattern](https://github.com/BumgeunSong/Krello/wiki/4.-Coordinator)

### Library

|                        | Version |           |
| ---------------------- | ------- | --------- |
| SwiftLint              |         | CocoaPods |
| FirebaseAuth           | 9.0.0   | CocoaPods |
| FirebaseFirestore      | 9.0.0   | CocoaPods |
| FirebaseFirestoreSwift | 9.0.0   | CocoaPods |

**Comment by BumgeunSong** [comment]
ㅋㅋㅋㅋ 프로필 사진까지!

저는 Library까지 별도로 쓰기보다는 '사용한 기술' 챕터에 그냥 같이 넣으면 어떨까 싶네요.

**Comment by BumgeunSong** [comment]
사용한 기술은 그냥 사용한 기술이라고 해도 괜찮을 거 같은데요?

**Comment by BumgeunSong** [comment]
깃헙 마크 다운에서 [접히는 토글 리스트](https://gist.github.com/Ashton-W/864d09d71f7cb8e5b47ebaac02b98455)도 만들 수 있어요. 그다지 중요한 부분이 아니라면 접어놓는 것도 좋을 듯

**Comment by BumgeunSong** [comment]
저는 개인적으로 팀 소개는 보너스 정도라고 생각을 해서, 맨 위에는 앱 소개랑 스크린샷이 먼저 올라갔으면 좋겠습니다! 팀 소개는 아래쪽으로 내리거나 접고요.

**Comment by BumgeunSong** [comment]
'고민과 해결' 파트가 있고 그게 좀 더 강조되었으면 좋겠어요! 이거는 위키에 작성하고 나서 어느 정도 수준으로 쓸지 결정하면 될 거 같아요

**Comment by BumgeunSong** [comment]
요런 느낌으로 정리하는 건 어떨지?

| 로그인  | 회원가입 | 
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/12508578/169458093-d3af10aa-0eb4-40df-ae8a-e8b0241e3e20.png" width="318" height="562"/>  | ![signup](https://user-images.githubusercontent.com/12508578/169457888-b24c62fc-9301-4a28-aa0e-081f79b083c3.gif)  | 
| - Firebase authentication 을 사용해 email 로그인을 할 수 있습니다. <br/>- 로그인을 하면 firestore 로 부터 인증을 하고 받아온 사용자 uid 를 local 에 저장해 API 호출에 사용합니다. <br/>- 한번 로그인을 하면 앱 종료 후 다시 실행해도 로그인 상태를 유지합니다.  |  - email, password 로 회원가입을 할 수 있습니다. <br/>- 입력값에 대한 검증을 하고 유효한 값인지 체크합니다. <br/>- 모든 TextField 의 값이 유효하다고 판단이 되면 비로소 회원가입 버튼이 활성화됩니다.  | 

| 할일 관리  | 드래그 앤 드랍 | 
| ------------- | ------------- |
| ![Board](https://user-images.githubusercontent.com/12508578/169457961-67a38d95-2543-407d-9671-280d22231747.gif)  | ![TaskMove](https://user-images.githubusercontent.com/12508578/169458030-758b38a1-2583-497b-a035-d7bdd2a3ad3e.gif)  |
| - 사용자 키(uid) 에 해당하는 데이터를 firestore 로 부터 불러와 화면에 보여줍니다.  | - Drag & Drop 으로 할일을 이동시킬 수 있습니다.(서버에 반영하는 작업은 구현 안됨) |

**Comment by Jinsujin** [comment]
역시 문서하면 에디지
